### PR TITLE
feat(codex): route Desktop Live voice through the local proxy

### LINKED ISSUE #5914: feat(codex): route Desktop Live voice through the local proxy
## Self Checks / 自检

- [x] I have read the FAQ and contribution guidelines.
- [x] I searched open and closed issues. This proposal is related to the user-facing failure in #5716, but focuses on the routing contract and maintenance boundaries.

## Related App / 涉及应用

Codex

## Problem or Motivation / 问题或动机

Codex Desktop Live voice uses two transports that are separate from normal Responses traffic:

1. an HTTP multipart request that creates a WebRTC call and returns a `Location` call ID; and
2. a WebSocket sideband connection bound to that call ID.

When Codex text traffic is routed to a third-party provider, the Live request currently follows the same custom base URL. A Responses-compatible provider normally does not implement the Live HTTP/WebSocket protocol, so the session fails with a missing `Location` or sideband error. Preserving the official ChatGPT login is not sufficient because CC Switch does not currently split Live traffic from text traffic.

## Proposed Solution / 建议方案

Add an opt-in **Codex Live voice** route to the local proxy, disabled by default, with three explicit billing policies:

- **Official ChatGPT account only**
- **Current provider only**
- **Official, then current provider**

The implementation should:

- proxy both call creation and the WebSocket sideband;
- bind each returned call ID to the provider that created it;
- rewrite successful `Location` headers back to the local sideband route;
- require third-party providers to explicitly declare Live capability and relative HTTP/WS endpoints;
- never forward OpenAI attestation to a third-party provider;
- isolate Live failures from Codex text-provider circuit-breaker accounting;
- reject Live when the proxy is not bound to loopback;
- cap request, response, frame, message, connection, and binding resources; and
- avoid fallback after a timeout or transport failure that may already have created a billable call.

### Third-party provider contract

A provider opting in must accept the original Live multipart request, return a `Location` whose final segment is an `rtc_*` ID or UUID, and accept a WebSocket sideband connection after `{call_id}` substitution. Responses API compatibility alone is not Live compatibility.

## Maintainer decisions requested / 需要维护者确认

1. **Official attestation boundary:** a working macOS prototype can generate the opaque proof by loading the DeviceCheck native module bundled in the installed, signed official ChatGPT app. It verifies the deep code signature, OpenAI Team ID, and bundle ID before loading anything. Is relying on that private installed-app module acceptable for CC Switch, or should official routing remain unsupported until OpenAI exposes a public contract?
2. **Outbound proxy support:** HTTP call creation can reuse CC Switch's global outbound proxy, but the first implementation's WebSocket sideband connects directly. Is that acceptable as a documented limitation for the initial version?
3. **Loopback authentication:** the route is loopback-only, but has no separate per-client token. Should a dedicated local client credential be required before merge?
4. **Platform scope:** third-party routing is platform-independent, while local official attestation is currently macOS/Apple Silicon only.

I have a focused implementation with Rust/TypeScript tests, English/Chinese/Japanese documentation, and sanitized screenshots ready for a Draft PR after this design is visible to maintainers.

### PR DESCRIPTION
**Pull request by wangjunjie007**
## Summary / 概述

This PR adds an opt-in Codex Desktop Live voice route to the CC Switch local proxy. It proxies both transports used by Live:

1. the HTTP request that creates a WebRTC call; and
2. the WebSocket Sideband connection bound to the returned call ID.

The feature is disabled by default and exposes three explicit quota policies:

- **Official ChatGPT account only**
- **Current provider only**
- **Official, then current provider**

Live traffic is isolated from Codex text failover health and never changes provider order.

## Why / 背景

Codex Desktop sends Live traffic to the configured Codex base URL. A provider that supports Responses API does not necessarily implement Live call creation, `Location` binding, or the Sideband WebSocket. Under a normal third-party Codex route this currently produces errors such as missing `Location` or an immediate voice disconnect.

This change gives Live an explicit routing contract instead of assuming that text compatibility implies realtime compatibility.

## What Changed / 改动

- Added `POST /live`, `/v1/live`, and `/codex/v1/live` call-creation routes.
- Added matching `GET .../:call_id` WebSocket Sideband routes.
- Rewrites a successful upstream `Location` back to the local proxy and binds the call ID to the exact provider that created it.
- Restores a binding after a failed Sideband setup, while generation-safe reservation prevents concurrent double-connects.
- Supports official ChatGPT OAuth, the current provider, or explicit official-to-current fallback.
- Requires third-party providers to opt in and configure relative creation and Sideband endpoints.
- Rejects Full URL provider configurations for Live in the backend, disables the incompatible UI state, and prevents it from being serialized.
- Adds a default-off switch under **Settings > General > Codex App Enhancements**.
- Adds English, Simplified Chinese, Traditional Chinese, and Japanese UI strings.
- Adds English, Chinese, and Japanese user documentation with sanitized screenshots.
- Rebased and revalidated against the CC Switch v3.19.1 mainline (`2852962`).

## Routing and Billing Semantics / 路由与额度

| Route                  | Behavior                                                                                                                        | Quota used                                          |
| ---------------------- | ------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| Official               | Uses the built-in OpenAI Official provider with ChatGPT OAuth                                                                   | ChatGPT subscription                                |
| Current provider       | Uses only the selected provider after explicit Live opt-in                                                                      | Current provider                                    |
| Official, then current | Tries official first; falls back only on `401`, `403`, `429`, or a preflight/connect failure known not to have sent the request | Official first, then current provider when eligible |

The fallback does not retry a `5xx`, timeout, redirect-followed connection failure, or another transport result that may already have created a billable call. This avoids duplicate billing and orphaned calls.

### Official ChatGPT route

1. Start the CC Switch local proxy and enable Codex takeover.
2. Keep the listener on `127.0.0.1`, `::1`, or `localhost`.
3. Sign in through Codex ChatGPT OAuth or the CC Switch managed Codex OAuth store.
4. Open **Settings > General > Codex App Enhancements**.
5. Enable **Live voice** and select **Official ChatGPT account only**.
6. Restart Codex Desktop if it was already running, then use the Live button.

The official route currently requires Apple Silicon macOS and a compatible signed official OpenAI desktop app for local DeviceCheck attestation.

### Third-party route

1. Open the Codex provider and expand **Advanced Options**.
2. Enable **Supports Codex Live voice** only after the upstream implements both transports.
3. Set the call creation endpoint, default `live`.
4. Set the Sideband endpoint template, default `live/{call_id}`.
5. Make that provider current and select **Current provider only**, or use the explicit fallback route.

The upstream must accept the Codex multipart `sdp` and `session` request, return a successful `Location` whose final segment is an `rtc_*` ID or UUID, and accept the Sideband WebSocket after `{call_id}` substitution. Responses API compatibility alone is not sufficient.

## Screenshots / 截图

| Live route settings                                                                                                                                                | Third-party Live capability                                                                                                                                                   |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Codex Live settings | Codex Live provider capability |

| 中文设置                                                                                                                                                           | 中文供应商配置                                                                                                                                                           |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| Codex Live 中文设置 | Codex Live 中文供应商配置 |

## Security and Failure Handling / 安全与故障处理

- Default off and loopback-only; both listener and request `Host` are validated.
- Rejects browser `Origin` and `Sec-Fetch-*` traffic.
- Verifies the official desktop app deep signature, OpenAI Team ID, and bundle ID before loading its DeviceCheck module.
- Applies a strict official-header allowlist before injecting ChatGPT OAuth.
- Never forwards OpenAI attestation or client credentials to a third-party provider.
- Rejects absolute, traversing, query-bearing, fragmented, or malformed third-party endpoint paths.
- Fails closed before creating a call when an explicit CC Switch global outbound proxy is configured, because Sideband proxying is not implemented yet.
- Limits HTTP bodies, WebSocket messages and frames, pending bindings, active Sidebands, idle time, and write time.
- Logs only route and frame metadata, not audio, message bodies, OAuth tokens, provider credentials, or attestation contents.
- Live errors do not increment the text-provider circuit breaker.

## Validation / 验证

- [x] `node_modules/.bin/tsc --noEmit`
- [x] Prettier check for frontend sources and all three new manuals
- [x] Vitest: 89 files, 589 tests passed
- [x] `cargo fmt --all -- --check`
- [x] `cargo clippy --all-targets --all-features -- -D warnings`
- [x] Rust: 2288 unit tests passed, 3 intentionally ignored, 1 existing test filtered because it binds the actively used default port `15721`; all integration tests passed
- [x] Focused Live tests, including a real WebSocket handshake that selects the second offered subprotocol
- [x] `git diff --check`
- [x] Sanitized screenshot review and staged high-confidence secret scan

The local prototype has been manually exercised with a real Codex Desktop spoken Live session. The hardened branch has passed the full local regression suite on CC Switch v3.19.1, but it has not been validated in an automated real OAuth/DeviceCheck/billing environment; maintainer review remains required before release.

## Known Limitations and Maintainer Decisions / 已知限制与维护者决策

1. **Official attestation contract:** official routing loads the DeviceCheck module from the installed, signed official desktop app after signature and identity checks. Please confirm whether relying on this private installed-app component is acceptable, or whether official routing should wait for a public OpenAI contract.
2. **Local native process boundary:** loopback and browser-header checks stop ordinary web pages, but there is no unforgeable per-client credential. Another malicious process running as the same local user can forge the request headers and invoke the enabled route. A true capability would require a Codex client change or a maintainer-approved OS-specific peer identity design.
3. **Existing Sideband cancellation:** disabling Live or stopping the proxy rejects new handshakes but does not yet broadcast cancellation to an already established Sideband. Users must close the Live session first; otherwise the idle timeout remains the final bound.
4. **Outbound proxy support:** HTTP CONNECT/SOCKS WebSocket tunneling is not implemented. The implementation now fails closed before call creation whenever an explicit CC Switch global outbound proxy is configured.
5. **Settings persistence race:** the existing settings page submits full asynchronous snapshots without a revision/CAS protocol. Very rapid toggle and route changes may complete out of order. Please advise whether this PR should also serialize settings saves and make file replacement atomic, or whether that broader persistence fix belongs in a separate PR.
6. **Platform scope:** third-party routing is platform-independent, but local official attestation is currently Apple Silicon macOS only.

## Related Issue / 关联 Issue

Closes #5914

Related to #5716

## Checklist / 检查清单

- [x] TypeScript typecheck passes
- [x] Frontend and documentation formatting passes
- [x] Rust Clippy passes with warnings denied
- [x] User-facing strings are updated in all existing locales
- [x] Documentation and screenshots are included
- [x] Feature is disabled by default

### CODE REVIEW

**Comment by farion1231** [comment]
@codex review

File: src-tauri/src/proxy/live.rs [hunk 1]
```diff
@@ -0,0 +1,2136 @@
...
+    provider: &Provider,
+    endpoint: &str,
+    client_uri: &Uri,
+) -> Result<String, ProxyError> {
+    let base_url = adapter.extract_base_url(provider)?;
+    let endpoint = match client_uri.query() {
+        Some(query) => format!("{endpoint}?{query}"),
+        None => endpoint.to_string(),
+    };
+    Ok(adapter.build_url(&base_url, &endpoint))
```
[the remark this answers is not in the document]
Comment (wangjunjie007) [reply src-tauri/src/proxy/live.rs:982]: Addressed in a66d348. Third-party providers with Full URL mode are now rejected by the backend Live route builder, while the Codex provider form disables and clears Live in Full URL mode and guards save-time serialization. Frontend and Rust regression coverage plus localized documentation were added. Verified with TypeScript, all 589 Vitest tests, cargo fmt, Clippy with -D warnings, and the full Rust test suite.

**Comment by wangjunjie007** [comment]
@codex review

Please review the latest commit `a66d348`, including the resolved Full URL provider handling for Codex Live.

**Comment by wangjunjie007** [comment]
@codex review

Please review the latest commit `a66d348`.

File: src-tauri/src/proxy/live.rs [hunk 2]
```diff
@@ -0,0 +1,2157 @@
...
+                attestation,
+                created_at: Instant::now(),
+                generation: uuid::Uuid::new_v4(),
+                phase: LiveCallBindingPhase::Available,
+            },
+        );
+        drop(calls);
+
+        let local_location = local_sideband_location(parts.uri.path(), &call_id)?;
+        response_headers.insert(http::header::LOCATION, local_location);
```
[the remark this answers is not in the document]
Comment (wangjunjie007) [reply src-tauri/src/proxy/live.rs]: Fixed in `fa5213e`. The upstream `Location` is now parsed as a URI, and its raw query is preserved in the rewritten local sideband `Location`, so `live_upstream_url` forwards required `intent` or token parameters. Added coverage for relative and absolute Locations plus percent-encoded query values. Validation: 26 Live module tests passed, and Clippy passed with `-D warnings`.

**Comment by wangjunjie007** [comment]
@codex review

Please review the latest rebased commit `8a9df4f`, including the fix that preserves upstream Live `Location` query parameters.

File: src-tauri/src/proxy/live.rs [hunk 3]
```diff
@@ -0,0 +1,2201 @@
...
+}
+
+fn extract_live_call_id(location: &str) -> Option<&str> {
+    location
+        .split('?')
+        .next()
+        .unwrap_or(location)
+        .trim_end_matches('/')
+        .rsplit('/')
+        .find(|segment| is_valid_call_id(segment))
```
[the remark this answers is not in the document]
Comment (wangjunjie007) [reply src-tauri/src/proxy/live.rs]: Fixed in `5c09a04`. Call ID extraction now validates only the final non-empty path segment, so `/v1/live/rtc_test/status` is rejected while `/v1/live/rtc_test/` remains supported. Validation: all 26 Live module tests passed, Rustfmt passed, and Clippy passed with `-D warnings`.

**Comment by wangjunjie007** [comment]
@codex review

Please review the latest commit `5c09a04`, including the fix that requires the Live call ID to be the final non-empty `Location` path segment.

**Comment by chenx-dust** [comment]
Really nice feature. Could you please merge this pull request? @farion1231

**Comment by 2218164692** [comment]
@farion1231 这个分支在下个版本会合并吗？
