### ISSUE TITLE
feat(codex): route Desktop Live voice through the local proxy

### ISSUE THREAD

**Issue by wangjunjie007** [farion1231/cc-switch#5914]
## Self Checks / 自检

- [x] I have read the FAQ and contribution guidelines.
- [x] I searched open and closed issues. This proposal is related to the user-facing failure in #5716, but focuses on the routing contract and maintenance boundaries.

## Related App / 涉及应用

Codex

## Problem or Motivation / 问题或动机

Codex Desktop Live voice uses two transports that are separate from normal Responses traffic:

1. an HTTP multipart request that creates a WebRTC call and returns a `Location` call ID; and
2. a WebSocket sideband connection bound to that call ID.

When Codex text traffic is routed to a third-party provider, the Live request currently follows the same custom base URL. A Responses-compatible provider normally does not implement the Live HTTP/WebSocket protocol, so the session fails with a missing `Location` or sideband error. Preserving the official ChatGPT login is not sufficient because CC Switch does not currently split Live traffic from text traffic.

## Proposed Solution / 建议方案

Add an opt-in **Codex Live voice** route to the local proxy, disabled by default, with three explicit billing policies:

- **Official ChatGPT account only**
- **Current provider only**
- **Official, then current provider**

The implementation should:

- proxy both call creation and the WebSocket sideband;
- bind each returned call ID to the provider that created it;
- rewrite successful `Location` headers back to the local sideband route;
- require third-party providers to explicitly declare Live capability and relative HTTP/WS endpoints;
- never forward OpenAI attestation to a third-party provider;
- isolate Live failures from Codex text-provider circuit-breaker accounting;
- reject Live when the proxy is not bound to loopback;
- cap request, response, frame, message, connection, and binding resources; and
- avoid fallback after a timeout or transport failure that may already have created a billable call.

### Third-party provider contract

A provider opting in must accept the original Live multipart request, return a `Location` whose final segment is an `rtc_*` ID or UUID, and accept a WebSocket sideband connection after `{call_id}` substitution. Responses API compatibility alone is not Live compatibility.

## Maintainer decisions requested / 需要维护者确认

1. **Official attestation boundary:** a working macOS prototype can generate the opaque proof by loading the DeviceCheck native module bundled in the installed, signed official ChatGPT app. It verifies the deep code signature, OpenAI Team ID, and bundle ID before loading anything. Is relying on that private installed-app module acceptable for CC Switch, or should official routing remain unsupported until OpenAI exposes a public contract?
2. **Outbound proxy support:** HTTP call creation can reuse CC Switch's global outbound proxy, but the first implementation's WebSocket sideband connects directly. Is that acceptable as a documented limitation for the initial version?
3. **Loopback authentication:** the route is loopback-only, but has no separate per-client token. Should a dedicated local client credential be required before merge?
4. **Platform scope:** third-party routing is platform-independent, while local official attestation is currently macOS/Apple Silicon only.

I have a focused implementation with Rust/TypeScript tests, English/Chinese/Japanese documentation, and sanitized screenshots ready for a Draft PR after this design is visible to maintainers.

**Comment by ZhangHouhou** [comment]
很希望上这个功能，这个voice 功能开发一点儿插件 配合用来学 English 会很合适~
